services:
    faucet:
        build:
            dockerfile_inline: |
                FROM php:8.4-apache
                RUN a2enmod rewrite remoteip
                RUN echo "RemoteIPHeader X-Forwarded-For\nRemoteIPInternalProxy 172.16.0.0/12" > /etc/apache2/conf-available/remoteip.conf
                RUN a2enconf remoteip
                RUN apt-get update && apt-get install -y ca-certificates && docker-php-ext-install mysqli pdo pdo_mysql
        image: emfox/faucet-apache-php
        volumes:
            - .:/var/www/html
            - /etc/localtime:/etc/localtime:ro
        environment:
            - VIRTUAL_HOST=faucet.d.evco.in
            - LETSENCRYPT_HOST=faucet.d.evco.in
            - LETSENCRYPT_EMAIL=emfoxzhou@gmail.com
        networks:
            - nginx-proxy
            - default
    faucet-mysql:
        image: mysql:8.4
        volumes:
            - "./mysql-data:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
        networks:
            - default
        secrets:
        - db_password
networks:
    default:
    nginx-proxy:
        name: nginx-proxy_default
        external: true
secrets:
    db_password:
        file: ./db_password.txt
